###
GET http://hmapi.detskie-sady.com/properties
Accept: application/json;
Content-Type: application/json
Authorization: Bearer 9j7kZWYpjHrpLOaXUv8g1tV5bNom5JOi


###
GET http://hmapi.detskie-sady.com/properties?expand=propertiesItems
Accept: application/json;
Content-Type: application/json
Authorization: Bearer 9j7kZWYpjHrpLOaXUv8g1tV5bNom5JOi


###
GET http://hmapi.detskie-sady.com/properties-items
Accept: application/json;
Content-Type: application/json
Authorization: Bearer 9j7kZWYpjHrpLOaXUv8g1tV5bNom5JOi

